# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_Automation.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(599, 401)
        font = QtGui.QFont()
        font.setFamily("Arial")
        MainWindow.setFont(font)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MainWindow.setWindowTitle("PO Automation")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(280, 280, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1.setGeometry(QtCore.QRect(180, 280, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.pushButton_1.setFont(font)
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(180, 250, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(180, 220, 93, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 599, 23))
        self.menubar.setObjectName("menubar")
        self.menuMain = QtWidgets.QMenu(self.menubar)
        self.menuMain.setObjectName("menuMain")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_Token = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.actionLoad_Token.setFont(font)
        self.actionLoad_Token.setObjectName("actionLoad_Token")
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionManual = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.actionManual.setFont(font)
        self.actionManual.setObjectName("actionManual")
        self.menuMain.addAction(self.actionLoad_Token)
        self.menuMain.addAction(self.actionExport)
        self.menuMain.addAction(self.actionClose)
        self.menuHelp.addAction(self.actionManual)
        self.menubar.addAction(self.menuMain.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.pushButton_3.clicked.connect(self.pushButton_3.click)
        self.pushButton.clicked.connect(self.pushButton.click)
        self.pushButton_1.clicked.connect(self.pushButton_1.click)
        self.pushButton_2.clicked.connect(self.pushButton_2.click)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.pushButton_1, self.pushButton_2)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.pushButton_2.setText(_translate("MainWindow", "Process"))
        self.pushButton_1.setText(_translate("MainWindow", "Preview"))
        self.pushButton.setText(_translate("MainWindow", "Load Token"))
        self.pushButton_3.setText(_translate("MainWindow", "Export Log"))
        self.menuMain.setTitle(_translate("MainWindow", "&Main"))
        self.menuHelp.setTitle(_translate("MainWindow", "Info"))
        self.actionLoad_Token.setText(_translate("MainWindow", "Load Token"))
        self.actionExport.setText(_translate("MainWindow", "Export"))
        self.actionClose.setText(_translate("MainWindow", "Exit"))
        self.actionManual.setText(_translate("MainWindow", "Manual"))
